version: "3"
services:
  anvil-uplink:
    # if something fails or the server is restarted, the container will restart
    restart: always 
    container_name: anvil-uplink
    image: anvil-uplink
    volumes:
      # - /home/bitnami/docker_files:/docker_files
      - ./:/docker_files
    working_dir: /docker_files
    build: 
      # build the image from the Dockerfile in the current directory
      context: .